import javax.xml.parsers.DocumentBuilderFactory
import java.io.ByteArrayOutputStream
import groovy.io.FileType

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.0'
	id 'io.spring.dependency-management' version '1.1.4'
	id "com.github.node-gradle.node" version "7.0.1"
}

group = 'org.lab4.wed'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

// yarn build
task buildFront(type: YarnTask) {
  args = ['build']
}

yarn_install.dependsOn(yarn_cache_clean) // очистка кэша перед yarn install
buildFront.dependsOn(yarn_install) // запуск yarn_install перед buildFront
processResources.dependsOn(buildFront) // запуск buildFront на этапе жизненного цикла gradle processResources(самом начальном, чтобы он смог попасть в конечный jar)

repositories {
	mavenCentral()
}

// доустановка node.js в сборку
node {
	download=true
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.4'
	compileOnly 'org.projectlombok:lombok'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'org.seleniumhq.selenium:selenium-java:4.23.0'
}

test {
	useJUnitPlatform()
}


// compileJava{
//     options.failOnError = false
// }

//compile
tasks.register('compileProject') {
    description = 'compile project'
    dependsOn 'classes'
    doLast{
        println 'Compile project...'
    }
}


//historyForCompile
tasks.register('hc') {
    mustRunAfter compileProject
    doLast{
        if (compileJava.state.failure != null) {
            def stash = 'git stash'.execute()
            stash.waitFor()

            def currentCommit = 'git rev-parse HEAD'.execute()
            currentCommit.waitFor()
            def currentBranch = 'git rev-parse --abbrev-ref HEAD'.execute()
            currentBranch.waitFor()
            def commitList = 'git rev-list HEAD'.execute()
            commitList.waitFor()

            println 'omg'
            if(stash.exitValue() == 0 && currentCommit.exitValue() == 0 && currentBranch.exitValue() == 0 && commitList.exitValue() == 0){
                currentCommit = currentCommit.text
                currentBranch = currentBranch.text
                commitList = commitList.text.split("\n")
                commitList.any { rev ->
                    println rev + 'lox'

                    def gitCheckoutBranch = 'git checkout ' + rev
                    gitCheckoutBranch.execute().waitFor()

                    def result = exec{
                        ignoreExitValue true
                        commandLine 'gradlew.bat', 'compileProject'
                    }

                    if(result.exitValue == 0){
                        def strGitDiffCommand = 'powershell git diff ' + commitList[0].toString() + ' ' + commitList[2].toString() + ' > build/diff.txt'
                        def gitDiff = strGitDiffCommand.execute().waitFor()

                        println ' > [TASK HISTORY]: RECompile Project: Success! yep yep'
                        true
                    }else{
                        println ' > [TASK HISTORY]: RECompile Project: lose! :('
                    }
                }
            }else{
                println ' > [TASK HISTORY COMPILE]: FAILURE'
            }
            def gitCheckoutBranch = 'git checkout ' + currentBranch
            gitCheckoutBranch.execute().waitFor()
            if(stash.exitValue() == 0){
                def stashPop = 'git stash pop'.execute().waitFor()
            }
        }
        println 'History compile'
    }
}

task ttt(){
    doLast{
        println 'gfjhjhjhjhfg'
    }
}

task xxx(){
    doLast{
        def stash = 'git stash'.execute()
        stash.waitFor()

        def currentCommit = 'git rev-parse HEAD'.execute()
        currentCommit.waitFor()
        def currentBranch = 'git rev-parse --abbrev-ref HEAD'.execute()
        currentBranch.waitFor()
        def commitList = 'git rev-list HEAD'.execute()
        commitList.waitFor()

        def stashPop = 'git stash pop'.execute()
        stashPop.waitFor()

        if(stash.exitValue() == 0 && currentCommit.exitValue() == 0 && currentBranch.exitValue() == 0 && commitList.exitValue() == 0){
            currentCommit = currentCommit.text
            currentBranch = currentBranch.text
            commitList = commitList.text.split("\n")
            println stash
            println currentCommit
            println currentBranch
            println commitList
            println stashPop
            println commitList[0].toString()
            println commitList[1].toString()
            def gitCheckoutBranch = 'git checkout ' + commitList[15].toString()
            gitCheckoutBranch.execute().waitFor()
            def result = exec{
                    ignoreExitValue true
                    commandLine 'gradlew.bat', 'ttt'
                }
        }
        // exec{
        //     ignoreExitValue = true
        //     commandLine 'git'
        // }
    }
}

//historyForBuild
tasks.register('hb') {
    mustRunAfter compileProject
    doLast{
        if (compileJava.state.failure != null) {
            println 'omg'
            def col = ['1', '2', '3', '4']
            col.any { count ->
                println count + 'lox'
                def result = exec{
                    ignoreExitValue true
                    commandLine 'gradlew.bat', 'compileProject'
                }
                if(result.exitValue == 0){
                    println ' > [TASK HISTORY]: RECompile Project: Success! yep yep'
                    exec{
                        ignoreExitValue true
                        commandLine 'gradlew.bat', 'buildProject'
                    }
                    true
                }else{
                    println ' > [TASK HISTORY]: RECompile Project: lose! :('
                }
            }
        }
        println 'History build'
    }
}

bootJar {
    mustRunAfter hb
    doLast{
        println 'bootJar'
    }
}

//build
task buildProject(type: Jar) {
    description 'build project'
    dependsOn 'compileProject'
    dependsOn 'hb'
    dependsOn 'bootJar'
    archiveFileName = 'WebLab4Application.jar'
    from sourceSets.main.output
    manifest {
        attributes(
                'Main-Class': 'org.lab4.wed.weblab4.WebLab4Application',
        )
    }
    doLast{
        println 'opopopopop'
    }
    
}

// project.gradle.buildFinished {
//     if (compileJava.state.failure != null) {
//         println 'omg'
//         def col = ['1', '2', '3', '4']
//         col.any { count ->
//             println count + 'lox'
//             def result = exec{
//                 ignoreExitValue true
//                 commandLine 'gradlew.bat', 'compileProject'
//             }
//             if(result.exitValue == 0){
//                 println ' > [TASK HISTORY]: RECompile Project: Success! yep yep'
//                 true
//             }else{
//                 println ' > [TASK HISTORY]: RECompile Project: lose! :('
//             }
//         }
//     }
// }

// project.gradle.buildFinished {
//     if (compileJava.state.failure != null) {
//         println compileProject.state.failure
//         println compileJava.state.failure
//         println "Crash compile"
//         def col = ['1', '2']
//         col.each { count ->
//             println count
//             exec{
//                 commandLine 'gradlew.bat', 'compileProject'
//             }
//         }
//     }
// }



task mems() {
    doLast{
        def col = ['1', '2', '3']
        col.each {count ->
            exec{
                workingDir '.'
                // commandLine 'gradlew.bat'
                // sleep(10 * 1000)
                // commandLine 'powershell', '-c', "./gradlew '--stop'"
                commandLine 'gradlew.bat', 'tet'
            }
            // commandLine 'powershell', '-c', "./gradlew '--stop'"
            // sleep(10 * 1000)
        }
    }
}



// Remove 'doLast' for die your PC, infinity starts processes Java SE, omg...
// task mems() {
//     doLast{
//         def col = ['1', '2', '3']
//         col.each {count ->
//             exec{
//                 commandLine 'powershell', '-c', "./gradlew 'tet'"
//             }
//         }
//     }
// }


//clean
task cleanProject(type: Delete) {
    delete 'build'
}

//xml - валидация всех xml-файлов в проекте
task xmlProject() {
    doLast {
        def xmlFiles = fileTree(dir: '/', include: '**/*.xml')
		println 'xmlFiles'
        xmlFiles.each { file ->
            try {
                def factory = DocumentBuilderFactory.newInstance()
                def builder = factory.newDocumentBuilder()
                builder.parse(file)
                println "XML-file '${file}' valied"
            } catch (Exception e) {
                println "XML-file '${file}' unvalied: ${e.message}"
            }
        }
    }
}

// history
