server:
  port: 8887
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s338963
    password: ${db-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show-sql: true
      format-sql: true

logging:
  level:
    root: INFO
