server:
  port: 8887
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${db_url}
    username: ${db_login}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show-sql: true
      format-sql: true

logging:
  level:
    root: INFO

